### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [2]:
#1.1
import numpy as np
def prime_numbers(n):
    prime = np.array([x for x in range(2, n+1) if all(x % y != 0 for y in range(2, int(x/2) +1))])
    return prime
prime=prime_numbers(20)
print(prime)

#1.2
print(prime[prime<10])
#1.3
print(prime[prime%2==0])


[ 2  3  5  7 11 13 17 19]
[2 3 5 7]
[2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [6]:
import numpy as np
a=np.random.randint(1,10,(4,4))
b=a[[1,3]]
c=a[2]
print(a,"\n")
print(b,"\n")
print(c,"\n")
print(a/c,"\n")


[[5 4 7 6]
 [7 9 1 4]
 [5 1 1 3]
 [4 5 4 6]] 

[[7 9 1 4]
 [4 5 4 6]] 

[5 1 1 3] 

[[1.         4.         7.         2.        ]
 [1.4        9.         1.         1.33333333]
 [1.         1.         1.         1.        ]
 [0.8        5.         4.         2.        ]] 



### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [ ]:
#3
acaso = np.random.rand(3, 10)
print(acaso)
indicies = np.argmin(np.abs(acaso-0.5), axis=1)
print(indicies)
#list of the values in acaso with index indicies
print(acaso[np.arange(3),indicies])
# 

[[0.65442546 0.33212232 0.83598895 0.57193785 0.52530455 0.38489424
  0.06399169 0.92559484 0.77447538 0.35147451]
 [0.49451491 0.33088978 0.1324159  0.87658422 0.41825227 0.60464934
  0.48190881 0.54100575 0.80979421 0.56779931]
 [0.44029179 0.202772   0.57186443 0.83474073 0.88554789 0.10075539
  0.05932916 0.1135988  0.83918235 0.88542004]]
[4 0 0]
[0.52530455 0.49451491 0.44029179]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [60]:
freqc=np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
maxhr=np.max(freqc)
print(maxhr)
minhr=np.min(freqc)
print(minhr)
sportindic = freqc > 120
print(sportindic)
count = np.sum(sportindic)
percO120 = (count/len(freqc))*100
print(percO120)




164
60
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
52.38095238095239


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [93]:
wages = np.array([50000, 105250, 55000, 89000], dtype=float)
wagesnew = wages.copy()
wagesnew[1] = wages[1] * 1.15
wagesnew[0] = wages[0] * 1.2
wagesnew[3] = wages[3] * 1.1
wagesnew[2] = wages[2] * 1.1
print(wagesnew)
cost= np.round(np.sum(wagesnew-wages),2)
print(cost)


[ 60000.  121037.5  60500.   97900. ]
40187.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [99]:
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])
#1
anni12 = survey_matrix[survey_matrix[:,2]>=12]
#print(anni12)
#2
redditi_anni=survey_matrix[survey_matrix[:,2]>=12, 1]
print(redditi_anni)
#3
redditi_anni_medio=np.mean(redditi_anni)
print(redditi_anni_medio)

[52000 63000 58000]
57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [107]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])
ages_clean=ages[ages!=999]
oldest=np.max(ages_clean)
print("Oldest citizen:", oldest)

Oldest citizen: 112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [ ]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]
paroleU =np.random.choice(lista_parole, 5)
testo ="In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva.\n " \
"Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono,\n" \
"i suoi occhi si spalancarono e lei esclamò una sola parola, __.\n"\
"Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __\n "\
"Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.\n"\
"Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:\n" \
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza __! Ci fu grande gioia e celebrazione.\n"
for i in range(5):
    testo=testo.replace("__", paroleU[i],1)
print(testo)

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico VANTAGGIO che proteggeva.
 Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il BIOGRAFIA come dono,
i suoi occhi si spalancarono e lei esclamò una sola parola, BIRILLO DA BOWLING.
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BATTERIA
 Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:
Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza VARIANTE! Ci fu grande gioia e celebrazione.



Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."